version: '3'
services:
 user-service:
  build: ./user-service
  cotainer_name: user-service
  ports: 
  - "4000:4000"

  order-service:
   build: ./order-service
   container_name: order-service
   ports: 
   - "5000:5000"

   depends_on: 
   - user-service